---
# defaults file for domain_wipe

libvirt_connect: "qemu:///system"
libvirt_host: localhost

virt_dom_name: "{{ inventory_hostname_short }}"

virt_dom_state: destroyed  # or shutdown ?

# remove/wipe the VM
virt_dom_undefine: false
# remove/wipe also the storage attached to the VM
virt_dom_remove_storage: false 
